---
  - name: Install client software
    become: True
    apt:
      state: present
      update_cache: yes
      cache_valid_time: 1800
      name:
        - krb5-user
        - krb5-pkinit
        - libldap-common
    when: ansible_distribution == "Debian"

  - name: Install client software
    become: True
    package:
      state: present
      name:
        - openldap
        - cyrus-sasl-gssapi
        - krb5
    when: ansible_distribution == "Archlinux"

  - name: Upload LDAP CA certificate
    become: True
    copy:
      content: "{{ lookup('file', 'ldapca.pem') }}"
      dest: "{{ auth_client_ca }}"
      owner: root
      group: root
      mode: 0644

  - name: Create kerberos configuration
    become: True
    template:
      src: krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0644

  - name: Create LDAP configuration
    become: True
    template:
      src: ldap.conf.j2
      dest: "{{ auth_client_ca | dirname }}/ldap.conf"
      owner: root
      group: root
      mode: 0644

  - include_tasks: account.yml
    with_items: "{{ auth_client_service_accounts }}"
